### ISSUE TITLE
needs license?

### ISSUE THREAD

**Issue by agokhale** [securitytemplates/sectemplates#4]
It would be cool to adopt a stated permissive license so it's clear how to adopt this for a given org, and what the expectations are for attibution/upstreaming.

**Comment by securitytemplates** [comment]
Hello agokhale,, 
Each individual program pack contains a modified "Creative Commons Attribution-NonCommercial 4.0 International" license. Have you seen this?  It is possible the licensing I chose has gaps, so I'd like to understand if your concerns above still hold true.

Thanks
Robert

**Comment by agokhale** [comment]
Oh sorry; I missed the licese in the modules - and the top level  Github license detector  didn't pick up the modules individual license.
Thanks for clarifying.  LGTM.

**Comment by securitytemplates** [comment]
No problem, reach out anytime if anything is fishy.
