### ISSUE TITLE
Retest/Validation of Remediation Solution

### ISSUE THREAD

**Issue by ncoblentz** [securitytemplates/sectemplates#5]
This is a great resource! As I was looking at the templates for vulnerability management, I see steps to remediate a particular vulnerability, but not to validate the remediation solution was successful. In many organizations, the security issues are tracked by the security team in addition to a product/infrastructure team, and that security team wants to see evidence that the fix applied successfully resolved all the risk. You might consider adding a step like that to the vulnerability management template.

**Comment by securitytemplates** [comment]
Hello Ncoblentz,
You're right, I did intentionally 'blackbox' remediation in the diagram and didn't get to this level of detail. I think your point is fair that this should be more explicit.

What are your thoughts on this updated diagram?
![VM1 2](https://github.com/user-attachments/assets/e11d4de8-a0e5-421e-85eb-01d2a593722c)

**Comment by ncoblentz** [comment]
I think that looks great!

**Comment by securitytemplates** [comment]
I'll publish an update probably later in the month. Thanks for the constructive feedback!

**Comment by securitytemplates** [comment]
Published https://github.com/securitytemplates/sectemplates/tree/main/vulnerability-management/v1
