### ISSUE TITLE
Threat modeling 

### ISSUE THREAD

**Issue by tuxerrante** [securitytemplates/sectemplates#6]
Hi,
Do you plan adding a threat modeling ([STRIDE](https://owasp.org/www-community/Threat_Modeling_Process#), PASTA, [cloud native](https://www.cncf.io/blog/2023/03/16/threat-modeling-to-cloud-native-we-need-a-new-approach/)...) chapter in the vulnerability management section?

I would expect it as the first step in proactive risk management since it could then be referenced from the following section about evaluating risk severity (which, to me, seems to not make clear enough the difference between  [vulnerability evaluation](https://www.first.org/cvss/v4.0/specification-document) and [risk evaluation](https://www.redhat.com/en/blog/why-cvss-does-not-equal-risk-how-think-about-risk-your-environment))

Thanks

**Comment by securitytemplates** [comment]
I wasn't planning on mentioning threat modeling frameworks for managing vulnerabilities. They are related, but different.  

I am slowly working on a security design review/threat modeling program pack which I will mention them. Personally, I don't use STRIDE/PASTA and most people I know doing threat modeling aren't using it either.

**Comment by securitytemplates** [comment]
Closing
